### PR TITLE
Fix StatusClassRenderer implementation

### LINKED ISSUE #89: Using flashmessage type based on string make error with extensions 1.x
#### Sonata packages

```
sonata-project/twig-extensions 1.x
```

## Subject
Flash message system from CoreBundle/twig-extensions 0.x will little change in twig-extensions 1.x. In old version user can add sonataFlashmessageType for anything. In extensions 1.x can do it only for object. 

## Steps to reproduce
Use `@SonataTwig/FlashMessage/render.html.twig` template to display flash message.
## Expected results
Correct dlsplaying flash message.

## Actual results
`Argument 1 passed to Sonata\Twig\Extension\StatusRuntime::statusClass() must be an object, string given`

## Solution
Fix `FlashManager` to work propertly with StatusClassRenderer:
- `Sonata\Twig\FlashMessage\FlashManager::handlesObject()`
- `Sonata\Twig\FlashMessage\FlashManager::getStatusClass()`

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

After add type hints in `Sonata\Twig\Extension\StatusRuntime` get status class from string (flash massage type) is not possible and `TypeError` is throwed. This PR fix `StatusClassRendererInterface` implementation in `FlashManager` and remove some type hints which make BC-break.

I am targeting this branch, because this change respect BC.

Closes #89.

## Changelog

```markdown
### Fixed
- Fix `Sonata\Twig\Status\StatusClassRendererInterface` implementation in `Sonata\Twig\FlashMessage\FlashManager`
- Fix `Sonata\Twig\Extension\StatusRuntime` to working with `Sonata\Twig\FlashMessage\FlashManager` again, after add type hints
```

### CODE REVIEW

**Comment by wbloszyk** [comment]
@phansys @core23 @VincentLanglet 
I close #90 becouse it is hard to understand. I will split it to more atomic PR to better understand what is changing:
- fix BC-break after add type hints - this PR
- improve FlashManager - another RP

This PR is RTM. Can you check it?

**Comment by wbloszyk** [comment]
@core23 @VincentLanglet @phansys @greg0ire Can you check it?

File: src/Extension/StatusRuntime.php [hunk 1]
```diff
@@ -35,9 +36,32 @@ public function addStatusService(StatusClassRendererInterface $renderer): void
...
+
+        if (\is_string($object)) {
+            return $this->statusClassForFlashManager($object, $statusType, $default);
+        }
+
+        @trigger_error(sprintf(
+            '"%s()" argument 1 must be instance of "%s" for StatusClassRenderer or "%s" for FlashManager - flash message type',
+            __METHOD__,
+            StatusClassRendererInterface::class,
+            'string'
```
Comment (phansys) [inline src/Extension/StatusRuntime.php:58]:
```suggestion
            'Argument 1 passed to "%s()" must be an instance of "%s" or a string, %s given.',
            __METHOD__,
            StatusClassRendererInterface::class,
            \is_object($object) ? 'instance of '.\get_class($object) : \gettype($object)
```

File: src/FlashMessage/FlashManager.php [hunk 2]
```diff
@@ -50,22 +50,46 @@ public function __construct(SessionInterface $session, array $types, array $cssC
...
+                $statusName = $object;
+            }
+            $object = $this;
+        }
+
+        if (!$object instanceof self) {
+            return false;
+        }
+
+        return  \array_key_exists($statusName, $this->cssClasses);
```
Comment (phansys) [inline src/FlashMessage/FlashManager.php:71]:
```suggestion
        return \array_key_exists($statusName, $this->cssClasses);
```

File: src/Extension/StatusRuntime.php [hunk 3]
```diff
@@ -35,9 +36,32 @@ public function addStatusService(StatusClassRendererInterface $renderer): void
...
-     * @param mixed $statusType
+     * @param object|string $object     Object for StatusClassRenderer or string for FlashManager
+     * @param string|null   $statusType Object status type or Sonata flash message type
+     * @param string        $default    Default status class
+     * @param mixed         $statusType
      */
-    public function statusClass(object $object, $statusType = null, string $default = ''): string
+    public function statusClass($object, $statusType = null, string $default = ''): string
+    {
+        if (\is_object($object)) {
```
Comment (phansys) [inline src/Extension/StatusRuntime.php:46]:
```suggestion
        if ($object instanceof StatusClassRendererInterface) {
```

Comment (wbloszyk) [reply src/Extension/StatusRuntime.php:46]: Here `$object` is handles by some `*StatusRenderer` class. `$object is not instanceof `StatusClassRendererInterface`.
```php
class OrderStatusRenderer implements StatusClassRendererInterface
{
    public function handlesObject($object, $statusName = null)
    {
        return ($object instanceof OrderInterface || $object instanceof OrderElementInterface)
            && \in_array($statusName, ['delivery', 'payment', null], true);
    }
    ...
}
```

File: src/FlashMessage/FlashManager.php [hunk 4]
```diff
@@ -50,22 +50,46 @@ public function __construct(SessionInterface $session, array $types, array $cssC
...
-            ? $this->cssClasses[$object]
+        if (\is_string($object)) {
+            if (null === $statusName) {
+                $statusName = $object;
+            }
+        }
+
+        return \array_key_exists($statusName, $this->cssClasses)
+            ? $this->cssClasses[$statusName]
             : $default;
```
Comment (phansys) [inline src/FlashMessage/FlashManager.php:93]:
```suggestion
        return $this->cssClasses[$statusName] ?? $default;
```

Comment (phansys) [reply src/FlashMessage/FlashManager.php:93]: Sorry, watching again I think you want to allow `null` to be a valid value.
Dismiss my suggestion in that case.

File: src/Extension/StatusRuntime.php (hunk 3 above)
Comment (phansys) [reply src/Extension/StatusRuntime.php:46]: IMO, if we know what union types it could be, I think is better to check against these types instead of relaxing the check just to `object`.

File: src/FlashMessage/FlashManager.php (hunk 4 above)
Comment (wbloszyk) [reply src/FlashMessage/FlashManager.php:93]: This can be do for FlashManager but not for StatusClassRenderer. I will mark it as `NEXT_MAJOR` in next RP 'Improve FlashManager`.

File: src/Extension/StatusRuntime.php (hunk 3 above)
Comment (phansys) [reply src/Extension/StatusRuntime.php:46]: Mhh, then, my suggestion was wrong [here](https://github.com/sonata-project/twig-extensions/pull/92/files#diff-05e712f490a9e8405b9e36c2136df8e9R57).
I'm leaving a new suggestion. Sorry for the misunderstanding.

File: src/Extension/StatusRuntime.php [hunk 5]
```diff
@@ -35,9 +36,32 @@ public function addStatusService(StatusClassRendererInterface $renderer): void
...
+        if (\is_string($object)) {
+            return $this->statusClassForFlashManager($object, $statusType, $default);
+        }
+
+        @trigger_error(sprintf(
+            'Argument 1 passed to "%s()" must be an instance of "%s" or a string, %s given.',
+            __METHOD__,
+            StatusClassRendererInterface::class,
+            \is_object($object) ? 'instance of '.\get_class($object) : \gettype($object)
+        ));
```
Comment (phansys) [inline src/Extension/StatusRuntime.php:59]:
```suggestion
            'Passing other type than object or string as argument 1 for "%s()" is deprecated since sonata-project/twig-extensions 1.x'
            .' and will throw an exception in version 2.0.' 
            __METHOD__
        ), E_USER_DEPRECATED);
```

File: src/Extension/StatusRuntime.php [hunk 6]
```diff
@@ -49,4 +73,35 @@ public function statusClass(object $object, $statusType = null, string $default
...
+            if ($flashManage->handlesObject($flashManage, $statusType)) {
+                if (null === $statusType) {
+                    $statusType = $object;
+                }
+
+                if ($flashManage->handlesObject($flashManage, $statusType)) {
+                    return $flashManage->getStatusClass($flashManage, $statusType, $default);
+                }
+            }
+        }
```
Comment (greg0ire) [inline src/Extension/StatusRuntime.php:89]:
```suggestion
        if ($flashManager = $this->getFlashManagerFromStatusServices()) {
            if ($flashManager->handlesObject($flashManager, $statusType)) {
                if (null === $statusType) {
                    $statusType = $object;
                }

                if ($flashManager->handlesObject($flashManage, $statusType)) {
                    return $flashManager->getStatusClass($flashManage, $statusType, $default);
                }
            }
        }
```

File: src/Extension/StatusRuntime.php [hunk 7]
```diff
@@ -49,4 +73,35 @@ public function statusClass(object $object, $statusType = null, string $default
...
+
+        return $default;
+    }
+
+    /**
+     * Get FlashManager if it is register as StatusClassRenderer.
```
Comment (greg0ire) [inline src/Extension/StatusRuntime.php:95]:
```suggestion
     * Get FlashManager if it is registered as StatusClassRenderer.
```

File: src/Extension/StatusRuntime.php (hunk 5 above)
Comment (wbloszyk) [reply src/Extension/StatusRuntime.php:59]: I remove `object` type hint to keep BC. It should be revert in 2.0. This message is little confusing for it. IMHO current message is OK. I will add in next `Improve FlashManager` another `error_triger` to tell people to avoid using `string` and use FlashManager directly instead.

Comment (phansys) [reply src/Extension/StatusRuntime.php:59]: I'm dizzy. Is `$object` intended to be an instance of `StatusClassRendererInterface`? If not, the current deprecation message is wrong.

Comment (wbloszyk) [reply src/Extension/StatusRuntime.php]: Oh, crap. Should be object or string. Can you recheck it?

Comment (phansys) [reply src/Extension/StatusRuntime.php]: IMO, the message you're using currently will be good for the exception, but it is not the best choice for a deprecation, where the version which deprecates the behavior must be explicitly exposed.
Even, please note that you're omitting the 2nd argument for `trigger_error()`, which for a deprecation should be `E_USER_DEPRECATED`.
I can't propose a better alternative than I've left at the beginning of this thread.

Comment (wbloszyk) [reply src/Extension/StatusRuntime.php]: i update it. This message can be modify in next PR, when I update documentation about FlashManager.

File: src/Extension/StatusRuntime.php [hunk 8]
```diff
@@ -35,9 +36,31 @@ public function addStatusService(StatusClassRendererInterface $renderer): void
...
+    {
+        if (\is_object($object)) {
+            return $this->statusClassForStatusClassRenderer($object, $statusType, $default);
+        }
+
+        if (\is_string($object)) {
+            return $this->statusClassForFlashManager($object, $statusType, $default);
+        }
+
+        @trigger_error(sprintf(
```
Comment (core23) [inline src/Extension/StatusRuntime.php:54]: INHO you can throw an exception, because you allow other objects than strings

Comment (wbloszyk) [reply src/Extension/StatusRuntime.php:54]: Technicly yes, but I want keep BC with 0.x version and revert `object` type hint in 2.0, after seperate FlashManager from StatusRenderer object.

File: tests/Extension/StatusRuntimeTest.php [hunk 9]
```diff
@@ -29,6 +29,10 @@ public function testStatusClassDefaultValue(): void
             ->willReturn(false);
 
         $runtime->addStatusService($statusService);
+        // getStatsClass() for StatusClassRenderer
```
Comment (greg0ire) [inline tests/Extension/StatusRuntimeTest.php:32]:
```suggestion
        // getStatusClass() for StatusClassRenderer
```

File: tests/Extension/StatusRuntimeTest.php [hunk 10]
```diff
@@ -29,6 +29,10 @@ public function testStatusClassDefaultValue(): void
...
         $this->assertSame('test-value', $runtime->statusClass(new \stdClass(), 'getStatus', 'test-value'));
+
+        // getStatsClass() for FlashManager
```
Comment (greg0ire) [inline tests/Extension/StatusRuntimeTest.php:35]:
```suggestion
        // getStatusClass() for FlashManager
```

**Comment by phansys** [comment]
Thank you @wbloszyk!

**Comment by benrcole** [comment]
I cant be certain because I don't fully understand how the engine works but I think there's a problem with StatusRuntime::statusClassForFlashManager that's included within this change.

 With this change my templates now render the flashes but the relevant css class is misssing for each flash type.  I think it's down to the below code fragment. My suspicion is that the wrong parameter is being sent to `handlesObject` below.

```
 private function statusClassForFlashManager(string $object, ?string $statusType = null, string $default = ''): string
    {
        if ($flashManager = $this->getFlashManagerFromStatusServices()) {
            if ($flashManager->handlesObject($flashManager, $statusType)) {
                if (null === $statusType) {
                    $statusType = $object;
                }
```

Sending `$object` instead of `$statusType` as below makes the templates render correctly

```
    private function statusClassForFlashManager(string $object, ?string $statusType = null, string $default = ''): string
    {
        if ($flashManager = $this->getFlashManagerFromStatusServices()) {
            if ($flashManager->handlesObject($flashManager, $object)) {
                if (null === $statusType) {
                    $statusType = $object;
                }
...
```
Is this a correct fix or am I missing some config somewhere else?

**Comment by wbloszyk** [comment]
@benrcole Look at https://github.com/sonata-project/twig-extensions/blob/1.x/docs/reference/status_helper.rst
and https://github.com/sonata-project/ecommerce/blob/3.x/src/Component/Order/OrderStatusRenderer.php

Change in remove src/FlashMessage/FlashManager.php fit it for correct way. Can you open issue for this with reproduction information?

Im also working on https://github.com/sonata-project/twig-extensions/pull/90 where using StatusClassRenderer and FlashManager will be more obvius.

**Comment by benrcole** [comment]
I have opened https://github.com/sonata-project/twig-extensions/issues/93 with reproducible steps
